/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author Fabys Castillo
 */
public class ViewBotonesListas extends javax.swing.JFrame {

    /**
     * Creates new form ViewBotonesListas
     */
    public ViewBotonesListas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        panelColores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cboColores = new javax.swing.JComboBox<>();
        cboUno = new javax.swing.JComboBox<>();
        cboDos = new javax.swing.JComboBox<>();
        cboTres = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelColores.setBackground(new java.awt.Color(111, 66, 111));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        cboColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Opcion", "Rojo", "Verde", "Azul", "Amarillo", "Gris", "Cyan" }));
        cboColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboColoresItemStateChanged(evt);
            }
        });
        cboColores.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboColoresPropertyChange(evt);
            }
        });

        cboUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200" }));
        cboUno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboUnoItemStateChanged(evt);
            }
        });

        cboDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200" }));
        cboDos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDosItemStateChanged(evt);
            }
        });

        cboTres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200" }));
        cboTres.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTresItemStateChanged(evt);
            }
        });

        jLabel1.setText("Rojo");

        jLabel2.setText("Verde");

        jLabel3.setText("Azul");

        javax.swing.GroupLayout panelColoresLayout = new javax.swing.GroupLayout(panelColores);
        panelColores.setLayout(panelColoresLayout);
        panelColoresLayout.setHorizontalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addComponent(cboTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(panelColoresLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelColoresLayout.setVerticalGroup(
            panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColoresLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboColoresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboColoresPropertyChange

    }//GEN-LAST:event_cboColoresPropertyChange

    private void cboColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboColoresItemStateChanged
        // TODO add your handling code here:
        
        String color = cboColores.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        int nrojo = Integer.valueOf(cboUno.getSelectedItem().toString());
        int nverde = Integer.valueOf(cboDos.getSelectedItem().toString());
        int nazul = Integer.valueOf(cboTres.getSelectedItem().toString());
        
        switch (color.toLowerCase()) {
        case "rojo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "verde": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break; 
        case "azul": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "amarillo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "gris": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "cyan": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
            }
    }//GEN-LAST:event_cboColoresItemStateChanged

    private void cboUnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboUnoItemStateChanged
        // TODO add your handling code here:
        String color = cboColores.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        int nrojo = Integer.valueOf(cboUno.getSelectedItem().toString());
        int nverde = Integer.valueOf(cboDos.getSelectedItem().toString());
        int nazul = Integer.valueOf(cboTres.getSelectedItem().toString());
        
        switch (color.toLowerCase()) {
        case "rojo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "verde": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break; 
        case "azul": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "amarillo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "gris": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "cyan": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
            }
    }//GEN-LAST:event_cboUnoItemStateChanged

    private void cboDosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDosItemStateChanged
        // TODO add your handling code here:
          String color = cboColores.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        int nrojo = Integer.valueOf(cboUno.getSelectedItem().toString());
        int nverde = Integer.valueOf(cboDos.getSelectedItem().toString());
        int nazul = Integer.valueOf(cboTres.getSelectedItem().toString());
        
        switch (color.toLowerCase()) {
        case "rojo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "verde": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break; 
        case "azul": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "amarillo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "gris": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "cyan": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
            }
    }//GEN-LAST:event_cboDosItemStateChanged

    private void cboTresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTresItemStateChanged
        // TODO add your handling code here:
        
         String color = cboColores.getSelectedItem().toString();
        System.out.println("Color " + color);
        
        int nrojo = Integer.valueOf(cboUno.getSelectedItem().toString());
        int nverde = Integer.valueOf(cboDos.getSelectedItem().toString());
        int nazul = Integer.valueOf(cboTres.getSelectedItem().toString());
        
        switch (color.toLowerCase()) {
        case "rojo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "verde": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break; 
        case "azul": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "amarillo": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "gris": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
        case "cyan": 
            panelColores.setBackground(new Color(nrojo, nverde, nazul));
            break;
            }
    }//GEN-LAST:event_cboTresItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBotonesListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBotonesListas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboColores;
    private javax.swing.JComboBox<String> cboDos;
    private javax.swing.JComboBox<String> cboTres;
    private javax.swing.JComboBox<String> cboUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel panelColores;
    // End of variables declaration//GEN-END:variables
}
